#!/usr/bin/env bash
#
# One-shot production deploy script for the News stack.
# Safe to re-run: first-time setup and rolling updates both go through here.
#
# Usage:
#   ./scripts/deploy.sh                       # full deploy (prompts on first run)
#   ./scripts/deploy.sh --init-env            # bootstrap .env interactively then exit (no deploy)
#   ./scripts/deploy.sh --skip-pull           # don't `git pull`
#   ./scripts/deploy.sh --skip-build          # reuse existing images
#   ./scripts/deploy.sh --skip-migrate        # don't run prisma migrate deploy
#   ./scripts/deploy.sh --skip-seed           # don't run admin seed
#   ./scripts/deploy.sh --skip-nginx-render   # keep nginx/default.conf as-is
#   ./scripts/deploy.sh -h | --help
#
# HTTPS is controlled by ENABLE_HTTPS in .env (true|false). Flip to true after
# obtaining a cert via certbot — see docs/NGINX_TLS.md. The script does NOT
# auto-detect cert files.
#
# Run from anywhere — the script cd's to the repo root.

set -euo pipefail

RED=$'\e[31m'; GRN=$'\e[32m'; YLW=$'\e[33m'; BLU=$'\e[34m'; RST=$'\e[0m'
log()  { printf '%s[deploy]%s %s\n' "$BLU" "$RST" "$*"; }
ok()   { printf '%s[ ok ]%s  %s\n' "$GRN" "$RST" "$*"; }
warn() { printf '%s[warn]%s %s\n' "$YLW" "$RST" "$*" >&2; }
die()  { printf '%s[err ]%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

SKIP_PULL=0
SKIP_BUILD=0
SKIP_MIGRATE=0
SKIP_SEED=0
SKIP_NGINX_RENDER=0
INIT_ENV_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-pull)          SKIP_PULL=1 ;;
    --skip-build)         SKIP_BUILD=1 ;;
    --skip-migrate)       SKIP_MIGRATE=1 ;;
    --skip-seed)          SKIP_SEED=1 ;;
    --skip-nginx-render)  SKIP_NGINX_RENDER=1 ;;
    --init-env)           INIT_ENV_ONLY=1 ;;
    -h|--help)            sed -n '3,21p' "$0"; exit 0 ;;
    *)                    die "Unknown flag: $1 (try --help)" ;;
  esac
  shift
done

# ── Helpers ────────────────────────────────────────────────────────────────────

# Strip scheme/path/port from a URL and return just the hostname.
url_to_domain() {
  local u="$1"
  u="${u#http://}"
  u="${u#https://}"
  u="${u%%/*}"
  u="${u%%:*}"
  printf '%s' "$u"
}

# Validate a bare domain like "news.example.com".
valid_domain() {
  [[ "$1" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)+$ ]]
}

# Interactive .env bootstrap. Writes .env from scratch (no sed against template)
# so user-supplied values with shell-special chars don't need escaping.
bootstrap_env() {
  [[ -t 0 ]] || die ".env missing and stdin is not a TTY — cannot prompt. Run interactively, or copy .env.production.example to .env and fill it in."

  log "First-time setup — answer a few questions to generate .env"
  echo

  # Domain
  local domain pub_url
  while true; do
    read -r -p "$(printf '%s' "$BLU")Domain (e.g. news.example.com)$(printf '%s' "$RST"): " domain
    domain="$(url_to_domain "$domain")"
    if valid_domain "$domain"; then
      pub_url="https://$domain"
      break
    fi
    warn "Invalid domain. Use a form like news.example.com (no scheme, no slash)."
  done

  # Admin username
  local admin_user
  read -r -p "$(printf '%s' "$BLU")Admin username [admin]$(printf '%s' "$RST"): " admin_user
  admin_user="${admin_user:-admin}"

  # Admin password — empty = auto-generate.
  # Reject single-quote and backslash to keep the .env line ($'...') unambiguous.
  local admin_pw admin_pw2
  while true; do
    read -r -s -p "$(printf '%s' "$BLU")Admin password (empty = auto-generate)$(printf '%s' "$RST"): " admin_pw
    echo
    if [[ -z "$admin_pw" ]]; then
      admin_pw="$(openssl rand -base64 24 | tr -d '\n=/+')"
      break
    fi
    if [[ "$admin_pw" == *\'* || "$admin_pw" == *\\* ]]; then
      warn "Password must not contain single-quote or backslash. Try again."
      continue
    fi
    read -r -s -p "$(printf '%s' "$BLU")Confirm password$(printf '%s' "$RST"): " admin_pw2
    echo
    if [[ "$admin_pw" == "$admin_pw2" ]]; then break; fi
    warn "Passwords don't match. Try again."
  done

  echo

  # Auto-generate secrets
  local pg_pass j_acc j_ref hmac
  pg_pass="$(openssl rand -hex 32)"
  j_acc="$(openssl rand -base64 48 | tr -d '\n')"
  j_ref="$(openssl rand -base64 48 | tr -d '\n')"
  hmac="$(openssl rand -base64 48  | tr -d '\n')"

  # Write .env. Single-quoting SEED_ADMIN_PASSWORD is safest: docker-compose
  # env-file parser treats single-quoted values as literal (no escape
  # processing). We've already rejected literal `'` and `\` in the password.
  cat > .env <<EOF
# Generated by scripts/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run \`./scripts/deploy.sh --init-env\` to regenerate (will refuse to overwrite).

# === Database ===
POSTGRES_USER=news
POSTGRES_PASSWORD=$pg_pass
POSTGRES_DB=news

# === JWT (three independent ≥32-char secrets — do NOT reuse) ===
JWT_ACCESS_SECRET=$j_acc
JWT_REFRESH_SECRET=$j_ref
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d

# === Click-tracking HMAC ===
HMAC_CLICK_SECRET=$hmac

# === Public origin ===
# Must match the domain served by nginx. Used for CORS, OG meta, cookies, HMAC.
PUBLIC_BASE_URL=$pub_url

# === HTTPS toggle ===
# false → nginx renders HTTP-only (port 80).
# true  → nginx renders HTTP→HTTPS redirect + HTTPS server block on 443.
#         Requires nginx/certs/fullchain.pem + privkey.pem (see docs/NGINX_TLS.md).
ENABLE_HTTPS=false

# === Admin seed (idempotent — same username on rerun = no-op) ===
SEED_ADMIN_USERNAME=$admin_user
SEED_ADMIN_PASSWORD='$admin_pw'
SEED_ADMIN_NAME=Admin
EOF

  chmod 600 .env

  ok ".env created (chmod 600)."
  echo
  log "Domain        : $pub_url"
  log "Admin user    : $admin_user"
  log "Admin password: $admin_pw"
  warn "Save the admin password — auto-generated values are not stored elsewhere."
  echo
}

# Render nginx/default.conf from PUBLIC_BASE_URL.
# Two layouts:
#   ENABLE_HTTPS=false → HTTP only on :80
#   ENABLE_HTTPS=true  → HTTP→HTTPS redirect + HTTPS on :443 (uses nginx/certs/*)
render_nginx_conf() {
  local domain="$1" enable_https="${2:-false}"
  mkdir -p nginx

  if [[ "$enable_https" == "true" ]]; then
    cat > nginx/default.conf <<NGINX
# AUTO-GENERATED by scripts/deploy.sh (--with-https variant) for: $domain
# Edits will be overwritten on next deploy. Pass --skip-nginx-render to preserve.
# To switch back to HTTP-only: set ENABLE_HTTPS=false in .env and re-run deploy.

upstream web_upstream {
  server web:6000;
  keepalive 32;
}

upstream api_upstream {
  server api:6001;
  keepalive 32;
}

# HTTP — redirect everything to HTTPS, but keep ACME challenge reachable for
# certbot webroot renewals (harmless 404 if you use --standalone instead).
server {
  listen 80;
  server_name $domain;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    try_files \$uri =404;
  }

  location / {
    return 301 https://\$host\$request_uri;
  }
}

# HTTPS
server {
  listen 443 ssl;
  http2 on;
  server_name $domain;

  client_max_body_size 50M;

  ssl_certificate     /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_session_tickets off;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/rss+xml;

  # Static uploads — served directly by nginx for performance
  location /uploads/ {
    alias /var/www/uploads/;
    expires 30d;
    add_header Cache-Control "public, immutable";
    access_log off;
  }

  # API
  location /api/ {
    proxy_pass http://api_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 60s;
  }

  # Next.js static assets
  location /_next/static/ {
    proxy_pass http://web_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  # Everything else → Next.js (SSR/ISR)
  location / {
    proxy_pass http://web_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 60s;
  }
}
NGINX
    ok "Rendered nginx/default.conf (HTTPS, server_name=$domain)."
  else
    cat > nginx/default.conf <<NGINX
# AUTO-GENERATED by scripts/deploy.sh (HTTP-only) for: $domain
# Edits will be overwritten on next deploy. Pass --skip-nginx-render to preserve.
# To enable HTTPS: obtain a cert via certbot (see docs/NGINX_TLS.md),
# place fullchain.pem + privkey.pem in nginx/certs/, then set
# ENABLE_HTTPS=true in .env and re-run ./scripts/deploy.sh.

upstream web_upstream {
  server web:6000;
  keepalive 32;
}

upstream api_upstream {
  server api:6001;
  keepalive 32;
}

server {
  listen 80;
  server_name $domain;

  client_max_body_size 50M;

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml application/rss+xml;

  # ACME http-01 challenge (used by certbot webroot mode if you mount it).
  # For certbot --standalone, this is harmless: nginx is stopped during issuance.
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
    try_files \$uri =404;
  }

  # Static uploads — served directly by nginx for performance
  location /uploads/ {
    alias /var/www/uploads/;
    expires 30d;
    add_header Cache-Control "public, immutable";
    access_log off;
  }

  # API
  location /api/ {
    proxy_pass http://api_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 60s;
  }

  # Next.js static assets
  location /_next/static/ {
    proxy_pass http://web_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  # Everything else → Next.js (SSR/ISR)
  location / {
    proxy_pass http://web_upstream;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 60s;
  }
}
NGINX
    ok "Rendered nginx/default.conf (HTTP-only, server_name=$domain)."
  fi
}

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
log "Checking prerequisites…"
command -v docker >/dev/null || die "docker not installed"
docker compose version >/dev/null 2>&1 || die "docker compose v2 plugin missing"
command -v openssl >/dev/null || die "openssl not installed"
command -v curl >/dev/null || die "curl not installed"

# ── 2. Bootstrap .env if missing (interactive) ────────────────────────────────
if [[ ! -f .env ]]; then
  bootstrap_env
fi

if [[ $INIT_ENV_ONLY -eq 1 ]]; then
  ok "--init-env: stopping here. Run ./scripts/deploy.sh again to deploy."
  exit 0
fi

# ── 3. Validate .env ──────────────────────────────────────────────────────────
# shellcheck disable=SC1091
set -a; source .env; set +a

for v in POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB \
         JWT_ACCESS_SECRET JWT_REFRESH_SECRET HMAC_CLICK_SECRET \
         PUBLIC_BASE_URL; do
  [[ -n "${!v:-}" ]] || die ".env missing required var: $v"
done

for s in JWT_ACCESS_SECRET JWT_REFRESH_SECRET HMAC_CLICK_SECRET; do
  val="${!s}"
  [[ "$val" == GENERATE_RANDOM_* ]] && die "$s still has placeholder value — edit .env"
  [[ ${#val} -ge 32 ]] || die "$s shorter than 32 chars (got ${#val})"
done

case "$PUBLIC_BASE_URL" in
  https://your-domain.com|http://localhost*|https://localhost*)
    warn "PUBLIC_BASE_URL=$PUBLIC_BASE_URL looks like a placeholder/dev value." ;;
esac

DOMAIN="$(url_to_domain "$PUBLIC_BASE_URL")"
valid_domain "$DOMAIN" || die "PUBLIC_BASE_URL ($PUBLIC_BASE_URL) does not contain a valid domain"

# Normalise ENABLE_HTTPS (default false).
case "${ENABLE_HTTPS:-false}" in
  true|TRUE|1|yes)  ENABLE_HTTPS=true ;;
  *)                ENABLE_HTTPS=false ;;
esac

if [[ "$ENABLE_HTTPS" == "true" ]]; then
  for f in nginx/certs/fullchain.pem nginx/certs/privkey.pem; do
    [[ -f "$f" ]] || die "ENABLE_HTTPS=true but $f is missing. See docs/NGINX_TLS.md"
  done
fi

ok "Pre-flight checks passed."

# ── 4. Render nginx/default.conf ──────────────────────────────────────────────
if [[ $SKIP_NGINX_RENDER -eq 0 ]]; then
  render_nginx_conf "$DOMAIN" "$ENABLE_HTTPS"
else
  warn "Skipping nginx render (--skip-nginx-render). Using existing nginx/default.conf."
fi

# ── 5. Pull ───────────────────────────────────────────────────────────────────
if [[ $SKIP_PULL -eq 0 && -d .git ]]; then
  log "git pull --ff-only"
  git pull --ff-only
elif [[ $SKIP_PULL -eq 1 ]]; then
  warn "Skipping git pull (--skip-pull)."
fi

# ── 6. Build images ───────────────────────────────────────────────────────────
if [[ $SKIP_BUILD -eq 0 ]]; then
  log "Building images (api, web, migrator)…"
  docker compose --profile migrate build --pull
  ok "Build complete."
else
  warn "Skipping build (--skip-build)."
fi

# ── 7. Bring up data layer ────────────────────────────────────────────────────
log "Starting postgres + redis…"
docker compose up -d postgres redis

wait_healthy() {
  local svc="$1" tries="${2:-30}" state cid
  for ((i=1; i<=tries; i++)); do
    cid="$(docker compose ps -q "$svc" 2>/dev/null || true)"
    if [[ -n "$cid" ]]; then
      state="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$cid" 2>/dev/null || echo unknown)"
      [[ "$state" == "healthy" ]] && return 0
    fi
    sleep 2
  done
  die "$svc did not become healthy in $((tries*2))s (last state: ${state:-unknown})"
}

wait_healthy postgres
wait_healthy redis
ok "Data layer healthy."

# ── 8. Migrate ────────────────────────────────────────────────────────────────
if [[ $SKIP_MIGRATE -eq 0 ]]; then
  log "Running prisma migrate deploy…"
  docker compose --profile migrate run --rm migrate
  ok "Migrations applied."
else
  warn "Skipping migrations (--skip-migrate)."
fi

# ── 9. Seed admin (idempotent) ────────────────────────────────────────────────
if [[ $SKIP_SEED -eq 0 ]]; then
  if [[ -z "${SEED_ADMIN_USERNAME:-}" || -z "${SEED_ADMIN_PASSWORD:-}" ]]; then
    warn "SEED_ADMIN_USERNAME / SEED_ADMIN_PASSWORD not set — skipping seed."
  else
    log "Seeding admin user '$SEED_ADMIN_USERNAME' (idempotent)…"
    docker compose --profile migrate run --rm \
      -e SEED_ADMIN_USERNAME -e SEED_ADMIN_PASSWORD -e SEED_ADMIN_NAME \
      migrate node_modules/.bin/tsx prisma/seed.ts
    ok "Admin seed complete."
  fi
else
  warn "Skipping seed (--skip-seed)."
fi

# ── 10. Start app layer ───────────────────────────────────────────────────────
log "Starting api, web, nginx…"
docker compose up -d api web nginx

# Force nginx to reload config (it may already be running from a prior deploy).
if docker compose ps --status running --services | grep -qx nginx; then
  docker compose exec -T nginx nginx -t >/dev/null 2>&1 \
    && docker compose exec -T nginx nginx -s reload \
    || warn "nginx config test failed or reload skipped — check: docker compose logs nginx"
fi
ok "Stack is up."

# ── 11. Health probe ──────────────────────────────────────────────────────────
log "Probing /api/health via nginx…"
probe_url="http://127.0.0.1/api/health"
[[ "$ENABLE_HTTPS" == "true" ]] && probe_url="https://127.0.0.1/api/health"
healthy=0
for ((i=1; i<=20; i++)); do
  if curl -fsSk --max-time 3 "$probe_url" >/dev/null 2>&1; then
    healthy=1; break
  fi
  sleep 3
done
if [[ $healthy -eq 1 ]]; then
  ok "/api/health returned 200."
else
  warn "Health probe failed after 60s. Check: docker compose logs --tail=200 api"
fi

echo
log "Container status:"
docker compose ps

echo
ok "Deploy finished."
ok "Admin login: ${PUBLIC_BASE_URL%/}/admin/login (user: ${SEED_ADMIN_USERNAME:-admin})"
[[ "$ENABLE_HTTPS" == "false" ]] && \
  log "HTTPS is off. To enable: obtain a cert (docs/NGINX_TLS.md), set ENABLE_HTTPS=true in .env, re-run."
